### ISSUE TITLE
bug: หน้า people "สรุปการลงมติในสภา" และหน้า votelog "บันทึกคะแนนเสียง" ไม่แสดง

### ISSUE THREAD

**Issue by mixth** [wevisdemo/they-work-for-us#50]
บริเวณด้านล่างนี้ไม่แสดงผล votelog

พบตั้งแต่ commit 53e390c43
เบื้องต้นพบว่า ID ที่ใช้สำหรับ match กับ people-vote ถูกเปลี่ยนไปเป็น UUID e.g. `f4c90a40-5485-5959-bcb3-a9ece6b0f871`

### People
![Screenshot 2023-03-18 192941](https://user-images.githubusercontent.com/6439183/226106333-02517a00-718c-4d24-9962-5bff94d23cda.png)

### Votelog
![Screenshot 2023-03-18 201058](https://user-images.githubusercontent.com/6439183/226108406-51cfba6b-eba8-40e3-99b4-7e9afc1b22bf.png)

**Comment by Th1nkK1D** [comment]
Fixed in a9d4e3d

It took me so long to figure out the problem as you mentioned that the id has become in UUID format since the upgrade. I found [a Gatsby plugin that transforms YAML doc](https://www.gatsbyjs.com/plugins/gatsby-transformer-yaml/?=gatsby-transformer-yaml) describes the behavior of id as follows:

>  If your data contains an id key the transformer will automatically convert this key to yamlId as id is a reserved internal keyword for Gatsby.

![image](https://user-images.githubusercontent.com/8860448/226654146-75c88447-ae73-43d5-9e66-61fac69d7a89.png)

So I need to remap the slug and query of the votelog to use `yamlId` instead of `id`.
